### ISSUE TITLE
Where i can find the  difinition for magic pattern file? 

### ISSUE THREAD

**Issue by sagasm** [awrznc/vscode-magic#1]

**Comment by awrznc** [comment]
@sagasm 

Here it is.
https://github.com/awrznc/vscode-magic/blob/61981bc13bb0cc9ceb1b148d38fac9b954a65214/syntaxes/magic.tmLanguage.json

Extensions and other information are defined below.
https://github.com/awrznc/vscode-magic/blob/620a60e6e7c68666b2f64724dcb44d21d21fcdf9/package.json

The manual for the magic pattern file itself can be found in the man command.
```bash
$ man magic
```

**Comment by awrznc** [comment]
Please open it again if necessary.
